### ISSUE TITLE
Spotify plays too fast and choppy with apulse

### ISSUE THREAD

**Issue by worldowner** [i-rinat/apulse#32]
Spotify 1.x requires pulseaudio. With apulse one can get sound, but it is choppy and too fast:
https://bbs.archlinux.org/viewtopic.php?id=203951

**Comment by i-rinat** [comment]
should be fixed by 24abf8d952fa32c2e1eb6e5aa2b21b8920b7f06d

**Comment by i-rinat** [comment]
Spotify client acts really dumb. It asks how many bytes could be written, and then writes 8192 bytes if value returned was greater than 0. Why? Didn't I just tell it that there is only 1024 bytes available in a buffer?

It happens that PulseAudio have only soft buffer size limit, and readily accepts all data.

**Comment by Witos** [comment]
https://github.com/i-rinat/apulse/commit/24abf8d952fa32c2e1eb6e5aa2b21b8920b7f06d + spotify 1.016.104 still doesn't work

**Comment by i-rinat** [comment]
> 24abf8d + spotify 1.016.104 still doesn't work

I've tested on the same exact version, 1.0.16.104. It was 64-bit, maybe that matters somehow.

Could you build debug version of apulse and collect stdout from Spotify client? (You configure with `cmake -DCMAKE_BUILD_TYPE=Debug ..` and compile as usual, `make`). Debug version will log all API function calls, so output could be large.

**Comment by i-rinat** [comment]
> It was 64-bit, maybe that matters somehow.

Tested 32-bit version. It works too,

**Comment by Witos** [comment]
@i-rinat 
Sorry, it works fine, apulse just picked up my old system wide libs instead of newly build ones.
